apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.35.0 (HEAD)
  labels:
    io.kompose.service: worker-node
  name: worker-node
spec:
  replicas: 3
  selector:
    matchLabels:
      io.kompose.service: worker-node
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.35.0 (HEAD)
      labels:
        io.kompose.service: worker-node
    spec:
      containers:
        - env:
            - name: RABBITMQ_HOST
              value: rabbitmq
          image: worker-node
          name: worker-node
          imagePullPolicy: Never
      restartPolicy: Always
