apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: worker-node-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: worker-node  # Matches deployment name
  minReplicas: 3
  maxReplicas: 10  # Scale up to 10 pods
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50  # Scale up if CPU > 50%
